inhibit_all_warnings!
platform :ios, '11.0'
use_frameworks!

pod 'ObjectMapper'
pod 'ReSwift'
pod 'Alamofire'

target 'Audienza' do
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'AlamofireNetworkActivityIndicator'
  pod 'PhoneNumberKit'
end

target 'AudienzaCore' do
  pod 'KeychainSwift'
end
